language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install requirements.txt . # install package + test dependencies
script: pytest tests # run tests
after_success:
  - codecov # submit coverage


