language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests
after_success:
  - coverage run -m pytest tests --include tests
  - coverage-badge -o coverage.svg
